letsencrypt:
  image: jrcs/letsencrypt-nginx-proxy-companion
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - ./certificates:/etc/nginx/certs:rw
  volumes_from:
    - nginx

nginx:
  image: jwilder/nginx-proxy
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
    - ./certificates:/etc/nginx/certs:ro
    - ./nginx/vhost.d:/etc/nginx/vhost.d
    - ./nginx/html:/usr/share/nginx/html
  ports:
    - 80:80
    - 443:443
  links:
    - app

postgres:
  image: postgres
  volumes:
    - /container-data/mattermost/dumps:/dumps
    - /container-data/mattermost/pgdata:/pgdata
  environment:
   - POSTGRES_PASSWORD=password
   - PGDATA=/pgdata

app:
  build: app
  links:
    - db:postgres
  volumes:
    - ./volumes/app/mattermost/config:/mattermost/config:rw
    - ./volumes/app/mattermost/data:/mattermost/data:rw
    - /etc/localtime:/etc/localtime:ro
  ports:
    - "3000:80"
  environment:
    VIRTUAL_HOST: mattermost.loomio.io
    LETSENCRYPT_HOST: mattermost.loomio.io
    LETSENCRYPT_EMAIL: rob@loomio.org
