[mattermost]
  [mattermost.enspiral]
  useAPI=true
  Server="chat.enspiral.com"
  Team="Enspiral"
  Login="rob+mattermostbot@loomio.org"
  Password="CsWtC4MQA78B"
  # PrefixMessagesWithNick=true

[slack]
  [slack.enspiral]
  useAPI=true
  Token="xoxb-83773971237-W8GsS8tcwJC68OLb8dRssI2s"

[[samechannelgateway]]
  name = slackmattermost
  enable = true
  accounts = [ "mattermost.enspiral","slack.enspiral" ]
  channels = [ "wellington", "thanks"]
